#scrape_configs:
  # <========================================================== k8s01 cluster
  - job_name: "k8s01-cluster-apiserver"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: https
    tls_config:
      ca_file: "kubernetes-sd-configs/k8s01-cluster/ca.crt"
      insecure_skip_verify: true
    bearer_token_file: "kubernetes-sd-configs/k8s01-cluster/sa-prometheus-token"
    # 重新标记
    relabel_configs:
      - source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
        separator: ";"
        action: keep
        regex: default;kubernetes;https
    # 基于kubernetes发现
    kubernetes_sd_configs:
      - api_server: "https://172.31.7.203:6443"
        tls_config:
          ca_file: "kubernetes-sd-configs/k8s01-cluster/ca.crt"
          #insecure_skip_verify: true
        bearer_token_file: "kubernetes-sd-configs/k8s01-cluster/sa-prometheus-token"
        role: endpoints

  - job_name: "k8s01-cluster-kubelet"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: https
    tls_config:
      ca_file: "kubernetes-sd-configs/k8s01-cluster/ca.crt"
      insecure_skip_verify: true
    bearer_token_file: "kubernetes-sd-configs/k8s01-cluster/sa-prometheus-token"
    # 重新标记
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
    # 基于kubernetes发现
    kubernetes_sd_configs:
      - api_server: "https://172.31.7.203:6443"
        tls_config:
          ca_file: "kubernetes-sd-configs/k8s01-cluster/ca.crt"
          #insecure_skip_verify: true
        bearer_token_file: "kubernetes-sd-configs/k8s01-cluster/sa-prometheus-token" 
        role: node

