#### 说明 
# 
# prometheus配置文件中的全局配置
#   在prometheus的配置文件prometheus.yml中其global:字段中进行配置
#
#### 结束

global:
  # 刮取目标上的metrics的超时时长,默认10s
  scrape_timeout: 10s

  # 从目标上刮取metrics的间隔时长,默认15s
  scrape_interval: 15s
  
  # 相关rules的评估时长,默认15s
  evaluation_interval: 15s

