#### 说明
#
#  Prometheus其prometheus.yaml中的job通过"静态配置(static_configs)"发现instances(实例)
#  参考：https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config
#     
#### 结束


#### 以node_exporter的实例为例
#
#scrape_configs:
  ## <==================================================================== prometheus
  - job_name: "prometheus"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    # 静态配置
    static_configs:
    - targets:
      - "172.31.7.201:9090"
      - "172.31.7.202:9090"

  ## <==================================================================== alertmanager
  - job_name: "alertmanager"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    # 静态配置
    static_configs:
    - targets:
      - "172.31.7.201:9093"
      - "172.31.7.202:9093"

  ## <==================================================================== wyc 生产环境
  - job_name: "wyc-prod-node-exporter"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    # 重新标记
    relabel_configs:
    # <== 添加标签(指定key和value)
    - source_labels: []
      separator: ""
      target_label: "project"
      replacement: 'wyc'
    - source_labels: []
      separator: ""
      target_label: "env"
      replacement: 'prod'
    # <== 添加标签(新key的value根据原有label的value)
    - source_labels:
      - "__address__"
      separator: ""
      regex: ([^:]+)(.*)
      target_label: "host"
      replacement: "${1}"
    # 静态配置
    static_configs:
    - targets: 
      - "172.31.7.201:9100"   # 9100是node_exporter默认监听的端口
      # labels:
      #  "project": "wyc"
      #  "env": "prod"

  #- job_name: "wyc-prod-minio"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 静态配置
  #  static_configs:
  #  - targets:
  #    - "IP:PROT"  
  #    # labels:
  #    #  "project": "wyc"
  #    #  "env": "prod"


  #- job_name: "wyc-prod-mysqld-exporter"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 静态配置
  #  static_configs:
  #  - targets:
  #    - "IP:PROT"  
  #    # labels:
  #    #  "project": "wyc"
  #    #  "env": "prod"


  #- job_name: "wyc-prod-mongodb-exporter"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 静态配置
  #  static_configs:
  #  - targets:
  #    - "IP:PROT"  
  #    # labels:
  #    #  "project": "wyc"
  #    #  "env": "prod"


  #- job_name: "wyc-prod-redis-exporter"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 静态配置
  #  static_configs:
  #  - targets:
  #    - "IP:PROT"  
  #    # labels:
  #    #  "project": "wyc"
  #    #  "env": "prod"


  #- job_name: "wyc-prod-rocketmq-exporter"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 静态配置
  #  static_configs:
  #  - targets:
  #    - "IP:PROT"  
  #    # labels:
  #    #  "project": "wyc"
  #    #  "env": "prod"


  #- job_name: "wyc-prod-nacos"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 静态配置
  #  static_configs:
  #  - targets:
  #    - "IP:PROT"  
  #    # labels:
  #    #  "project": "wyc"
  #    #  "env": "prod"


  ## <==================================================================== jmsco 生产环境
  - job_name: "jmsco-prod-node-exporter"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    # 重新标记
    relabel_configs:
    # <== 添加标签(指定key和value)
    - source_labels: []
      separator: ""
      target_label: "project"
      replacement: 'jmsco'
    - source_labels: []
      separator: ""
      target_label: "env"
      replacement: 'prod'
    # <== 添加标签(新key的value根据原有label的value)
    - source_labels:
      - "__address__"
      separator: ""
      regex: ([^:]+)(.*)
      target_label: "host"
      replacement: "${1}"
    # 静态配置
    static_configs:
    - targets:
      - "172.31.7.202:9100"  # 9100是node_exporter默认监听的端口
      # labels:
      #  "project": "wyc"
      #  "env": "jmsco"
