#### 说明
#
#  Prometheus其prometheus.yaml中的job通过"静态配置(static_configs)"发现instances(实例)
#  参考：https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config
#     
#### 结束


#### 以node_exporter的实例为例
#
#scrape_configs:
  ######## wyc 生产 环境
  - job_name: "wyc-prod-node-exporter"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    # <== 服务发现机制 之 file_sd_configs
    file_sd_configs:
    - files:
      - "file-sd-configs/wyc-project/prod/wyc-prod-node-exporter.yaml"
      # <== 刷新文件内容的间隔时间，默认5m
      refresh_interval: 2s

  #- job_name: "wyc-prod-minio"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-minio.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s
  #- job_name: "wyc-prod-mysql"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-mysql.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s
  #- job_name: "wyc-prod-mongodb"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-mongodb.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s
  #- job_name: "wyc-prod-redis"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-redis.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s
  #- job_name: "wyc-prod-rocketmq"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-rocketmq.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s
  #- job_name: "wyc-prod-nacos"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-nacos.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s

  ######## jmsco 生产 环境
  - job_name: "jmsco-prod-node-exporter"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    file_sd_configs:
    - files:
      - "file-sd-configs/jmsco-project/prod/jmsco-prod-node-exporter.yaml"
      # 刷新文件中内容的间隔时间，默认5m
      refresh_interval: 2s

