groups:
  - name: node_exporter 
    rules: 
    - alert: "Linux服务器或node-exporter进程已停止"
      for: 2m
      expr: up{job='wyc-prod-linux-servers'} == 0
      labels:
        severity: critical
      annotations:
        summary: "Job {{ $labels.job }} internal instance {{ $labels.instance }}"
        description: "实例停止 或 实例所在服务器停机"

    - alert: "Linux服务器内存使用率>90%"
      for: 2m
      expr: ( node_memory_MemTotal_bytes{job='wyc-prod-linux-servers'} - ( node_memory_MemFree_bytes{job='wyc-prod-linux-servers'} +  node_memory_Buffers_bytes{job='wyc-prod-linux-servers'} +  node_memory_Cached_bytes{job='wyc-prod-linux-servers'} ) ) / node_memory_MemTotal_bytes{job='wyc-prod-linux-servers'} * 100  > 90
      labels:
        severity: critical
      annotations:
        summary: "Job {{ $labels.job }} internal instance {{ $labels.instance }}"
        description: "实例所在服务器的内存使用率>90%" 

    - alert: "本地磁盘其block的使用率>80%"
      for: 2m
      expr: ( node_filesystem_size_bytes{job="wyc-prod-linux-servers",device=~"/de.*"} - node_filesystem_free_bytes{job="wyc-prod-linux-servers",device=~"/de.*"} )  / node_filesystem_size_bytes{job="wyc-prod-linux-servers",device=~"/de.*"}  * 100  > 80
      labels:
        severity: critical
      annotations:
        summary: "Job {{ $labels.job }} internal instance {{ $labels.instance }}"
        description: "实例所在服务器其磁盘 {{ $labels.device }}，挂载点 {{ $labels.mountpoint }}"

