#scrape_configs:
  ## <==================================================================== prometheus
  - job_name: "prometheus"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    # 基于文件发现
    file_sd_configs:
    - files:
      - "file-sd-configs/prometheus.yaml"
      refresh_interval: 2s

  ## <==================================================================== alertmanager
  - job_name: "alertmanager"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    # 基于文件发现
    file_sd_configs:
    - files:
      - "file-sd-configs/alertmanager.yaml"
      refresh_interval: 2s


  ## <==================================================================== wyc 生产环境
  - job_name: "wyc-prod-node-exporter"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    # 重新标记
    relabel_configs:
    # <== 添加标签(指定key和value)
    - source_labels: []
      separator: ""
      target_label: "project"
      replacement: 'wyc'
    - source_labels: []
      separator: ""
      target_label: "env"
      replacement: 'prod'
    # <== 添加标签(新key的value根据原有label的value)
    - source_labels:
      - "__address__"
      separator: ""
      regex: ([^:]+)(.*)
      target_label: "host"
      replacement: "${1}"
    # 基于文件发现
    file_sd_configs:
    - files:
      - "file-sd-configs/wyc-project/prod/wyc-prod-node-exporter.yaml"
      refresh_interval: 2s

  #- job_name: "wyc-prod-minio"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 文件发现
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-minio.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s

  #- job_name: "wyc-prod-mysqld-exporter"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 文件发现
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-mysqld-exporter.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s

  #- job_name: "wyc-prod-mongodb-exporter"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 文件发现
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-mongodb-exporter.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s

  #- job_name: "wyc-prod-redis-exporter"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 文件发现
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-redis-exporter.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s

  #- job_name: "wyc-prod-rocketmq-exporter"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 文件发现
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-rocketmq-exporter.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s

  #- job_name: "wyc-prod-nacos"
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  metrics_path: /metrics
  #  # 重新标记
  #  relabel_configs:
  #  # <== 添加标签(指定key和value)
  #  - source_labels: []
  #    separator: ""
  #    target_label: "project"
  #    replacement: 'wyc'
  #  - source_labels: []
  #    separator: ""
  #    target_label: "env"
  #    replacement: 'prod'
  #  # 文件发现
  #  file_sd_configs:
  #  - files:
  #    - "file-sd-configs/wyc-project/prod/wyc-prod-nacos.yaml"
  #    # 刷新文件中内容的间隔时间，默认5m
  #    refresh_interval: 2s


  ## <==================================================================== jmsco 生产环境
  - job_name: "jmsco-prod-node-exporter"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    # 重新标记
    relabel_configs:
    # <== 添加标签(指定key和value)
    - source_labels: []
      separator: ""
      target_label: "project"
      replacement: 'jmsco'
    - source_labels: []
      separator: ""
      target_label: "env"
      replacement: 'prod'
    # <== 添加标签(新key的value根据原有label的value)
    - source_labels:
      - "__address__"
      separator: ""
      regex: ([^:]+)(.*)
      target_label: "host"
      replacement: "${1}"
    # 文件发现
    file_sd_configs:
    - files:
      - "file-sd-configs/jmsco-project/prod/jmsco-prod-node-exporter.yaml"
      # 刷新文件中内容的间隔时间，默认5m
      refresh_interval: 2s
